// Copyright (c) Quinntyne Brown. All Rights Reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System.Text;

namespace CodeGenerator.DocsGen;

/// <summary>
/// Shared markdown-writing helpers. Every generated file carries the same banner so a
/// reader who opens one in an editor knows not to hand-edit it.
/// </summary>
public static class MarkdownEmitter
{
    public const string Banner =
        "<!-- AUTOGENERATED by eng/DocsGen. Do not edit; run `dotnet run --project eng/DocsGen`. -->";

    public static StringBuilder Page(string title, string description, int order)
    {
        var builder = new StringBuilder();
        builder.AppendLine("---");
        builder.AppendLine($"title: {Quote(title)}");
        builder.AppendLine($"description: {Quote(description)}");
        builder.AppendLine("sidebar:");
        builder.AppendLine($"  order: {order}");
        builder.AppendLine("---");
        builder.AppendLine();
        builder.AppendLine(Banner);
        builder.AppendLine();
        return builder;
    }

    /// <summary>
    /// YAML-quotes a scalar. Frontmatter values routinely contain a colon, which would
    /// otherwise be read as a mapping.
    /// </summary>
    public static string Quote(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    /// <summary>
    /// Escapes a value for use inside a markdown table cell. A literal pipe would end
    /// the cell, and a backtick-wrapped pipe still does.
    /// </summary>
    public static string Cell(string? value) =>
        string.IsNullOrEmpty(value) ? "—" : value.Replace("|", "\\|").Replace("\r", string.Empty).Replace("\n", " ");

    public static string Code(string? value) =>
        string.IsNullOrEmpty(value) ? "—" : $"`{value.Replace("|", "\\|")}`";

    /// <summary>
    /// When true, changes are reported but not written. Used by <c>--check</c>, which must
    /// leave the working tree untouched so CI can report drift without creating it.
    /// </summary>
    public static bool CheckOnly { get; set; }

    /// <summary>
    /// Writes <paramref name="content"/> only when it differs from what is already on
    /// disk, and always with LF endings so the drift gate does not fire purely because
    /// the generator ran on Windows.
    /// </summary>
    public static bool WriteIfChanged(string path, string content)
    {
        var normalized = content.Replace("\r\n", "\n");

        if (File.Exists(path))
        {
            var existing = File.ReadAllText(path).Replace("\r\n", "\n");
            if (string.Equals(existing, normalized, StringComparison.Ordinal))
            {
                return false;
            }
        }

        if (CheckOnly)
        {
            return true;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, normalized, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        return true;
    }
}
